apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: fib-knative-1
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/ibmcom/fib-knative
---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: fib-knative
  namespace: default 
spec:
  traffic:
  - configurationName: fib-knative-1
    percent: 100 # All traffic goes to fib-knative-1 
