apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fib-knative
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/beemarie/fib-knative.git
              revision: master
          template:
            name: kaniko
            arguments:
            - name: IMAGE
              value: docker.io/beemarie/fib-knative:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/beemarie/fib-knative:latest
            imagePullPolicy: Always
