apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: fib-knative-1
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/ibmcom/fib-knative # The URL to the sample image
---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: fib-knative # The name of our route; appears in the URL to access the app
  namespace: default 
spec:
  traffic:
  - configurationName: fib-knative-1
    percent: 100 # All traffic goes to this revision
